### ISSUE TITLE
Firefox create notice is not working.

### ISSUE THREAD

**Issue by aka-jain** [ncs-jss/HTTP_200#114]
@itaditya will you please solve it? It's urgent.

**Comment by itaditya** [comment]
On it , Sir ..

**Comment by itaditya** [comment]
Sir what is the administrative login details

**Comment by itaditya** [comment]
Sir , can you tell me what are the function calls when the create notice button is clicked . 

Currently , getting error installng django ....
I tried to find relevant JS functions for create notice but able to see its validation script only ,  is the functioning implemented through backend ? i'm in doubt , help me plz..

**Comment by aka-jain** [comment]
@itaditya I just got the solution but I want you to implement this. 
Try to remove setInterval from the validation script and instead of it use click or change function with checkbox. But still I got one more issue... rest of the checkboxes validation will not work then. 
So try to check it and solve it.

**Comment by abhayraw1** [comment]
Fixed.
