### ISSUE TITLE
Create a staff group in Admin.

### ISSUE THREAD

**Issue by RishabhJain2018** [ncs-jss/HTTP_200#133]

**Comment by RishabhJain2018** [comment]
@DESHRAJ sir this had been asked by natraj sir to give the staff people, attendants a user & the permissions will be same as that of student.

**Comment by DESHRAJ** [comment]
@RishabhJain2018 we have the group name `others` created in the django admin. There is no need to create some new group.

**Comment by RishabhJain2018** [comment]
@DESHRAJ sir I will have a talk about that with natraj sir.

**Comment by RishabhJain2018** [comment]
@DESHRAJ  okk sir.. i will have a talk with natraj sir about that.

**Comment by RishabhJain2018** [comment]
@DESHRAJ sir I had a talk with Natraj sir he said others group is ok. So I am closing this issue.
