### ISSUE TITLE
Integrate the feature of bookmarking a particular Notice

### ISSUE THREAD

**Issue by DESHRAJ** [ncs-jss/HTTP_200#15]
The usecase is that every user can bookmark any number of notices and we need to create a new Model for that named BookmarkedNotice that contain two fields notice_id(fk) and user_id(fk) so that later on we can show the filtered list of notices.

**Comment by DESHRAJ** [comment]
Fixed :+1:

**Comment by shriyanka** [comment]
@Deshraj 
This is not done have to create view for creating and updating.. Just created a template and listview now so work needs to be done.

**Comment by DESHRAJ** [comment]
Yes, I have seen that. I have coded the views last night and it's working now.

**Comment by shriyanka** [comment]
Cool :thumbs_up  :D
