### ISSUE TITLE
Change the title of pages from "JSS Connect" to "JSS InfoConnect"

### ISSUE THREAD

**Issue by deshraj** [ncs-jss/HTTP_200#160]

**Comment by RishabhJain2018** [comment]
@deshraj sir this is resolved. Should I close this issue ?

**Comment by deshraj** [comment]
See this 
![selection_023](https://cloud.githubusercontent.com/assets/2945708/20059421/343d7a22-a4c4-11e6-91e9-4a259ec8ad21.png)

**Comment by RishabhJain2018** [comment]
@deshraj Sir, please check now.

**Comment by deshraj** [comment]
Awesome. Fixed now. :+1: 
Closing it.
