### ISSUE TITLE
Integrate Backstroke to keep repository's forks up to date.

### ISSUE THREAD

**Issue by ankitjain28may** [ncs-jss/HTTP_200#163]
It automatically sends PR to all the repository's forks repo to merge the latest commit.

**Comment by RishabhJain2018** [comment]
@ankitjain28may I don't think it would be a good idea to integrate it. All the people who are currently contributing will automatically keep it updated.

@deshraj Sir, Please add your views.

**Comment by deshraj** [comment]
No, this is not a good idea to have. Closing it.

**Comment by ankitjain28may** [comment]
Ok Sir
