### ISSUE TITLE
Typo Error in Forgot Password template.

### ISSUE THREAD

**Issue by RishabhJain2018** [ncs-jss/HTTP_200#188]
Change the heading of forgot password page to `forgot password` from `forget password`.

**Comment by hoatran1403** [comment]
Can I help to fix this with a PR?

**Comment by RishabhJain2018** [comment]
@hoatran1403 yeah sure go ahead.

**Comment by hoatran1403** [comment]
Thanks @RishabhJain2018 . I've just created a PR with minor change .i'm not sure it can fix this bug or not since this is my first open source contribution ever. hope this help :+1:

**Comment by RishabhJain2018** [comment]
fixed #188 via #189 .
