### ISSUE TITLE
Update the requirements file

### ISSUE THREAD

**Issue by deshraj** [ncs-jss/HTTP_200#197]
Looks like some of the requirements are missing. Please update the requirements file.

**Comment by dhruvhacks** [comment]
@deshraj 
Sir, juniors will be covering this issue as a prerequisite to project [HTTP_200_Migration](https://github.com/ncs-jss/HTTP_200/projects/1)

**Comment by Mansi145** [comment]
@dhruvhacks sir & @deshraj sir I've updated the requirements file. Please review it.
