### ISSUE TITLE
update django-debug-toolbar==1.5

### ISSUE THREAD

**Issue by prakharchoudhary** [ncs-jss/HTTP_200#211]
The current version `django-debug-toolbar==1.4` results in  an error `TypeError: process() takes exactly 3 arguments (2 given)`

**Comment by RishabhJain2018** [comment]
@prakharchoudhary Don't open unnecessary issues as issue #197 is opened regarding the same. First check your issue in the existing ones, if it doesn't exists then open it.

**Comment by prakharchoudhary** [comment]
@RishabhJain2018 My apologies. I will take care from next time.
