### ISSUE TITLE
Update Quick Links of all templates.

### ISSUE THREAD

**Issue by dhruvhacks** [ncs-jss/HTTP_200#235]
Most of the links in 'Quick Links' section are broken and must be fixed.

**Comment by dhruvhacks** [comment]
@RishabhJain2018 Is this link restructuring fine??
![image](https://user-images.githubusercontent.com/15031475/42469779-554ef2e8-83d6-11e8-85c3-543454b1ee12.png)

**Comment by RishabhJain2018** [comment]
Yes! LGTM :)
