### ISSUE TITLE
Include last_seen feature with every authenticated user 

### ISSUE THREAD

**Issue by DESHRAJ** [ncs-jss/HTTP_200#24]
For every user, we need to have a last_seen feature. This will include two types of messages: 

1. Read messages
2. Unread messages

We need to maintain these two categories for every user.

**Comment by DESHRAJ** [comment]
We will do it later Kajal. We will get this feature in 1.2 version. Let's first try to roll 1.1 as we get the frontend ready.

**Comment by shriyanka** [comment]
Ok sure. Can you please put labels on the issues of v 1.1 ?? 
Its slightly confusing as I don't know the discussions related to this project.

**Comment by DESHRAJ** [comment]
this issue is same as #16 and hence closing it.
