### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by RishabhJain2018** [ncs-jss/HTTP_200#243]
@dhruvhacks Can you please take a look at this?
<img width="737" alt="screenshot 2018-12-25 at 5 35 27 pm" src="https://user-images.githubusercontent.com/12206047/50427067-8c4ead00-086b-11e9-969c-50dbdf742077.png">

**Comment by dhruvhacks** [comment]
@RishabhJain2018 
Sir, juniors will be covering this issue in #197 !

**Comment by Mansi145** [comment]
@dhruvhacks sir & @RishabhJain2018 sir I've resolved this issue. Please review it.

**Comment by RishabhJain2018** [comment]
Thanks, @Mansi145 for fixing this 🎉 
When I left @dhruvhacks was leading the project, so he will be the one merging it.
