### ISSUE TITLE
Notice update and notice delete option for the faculties

### ISSUE THREAD

**Issue by DESHRAJ** [ncs-jss/HTTP_200#25]

**Comment by Shivam1904** [comment]
Pull request #37 - Everything is done, only the redirection for unauthorized user is to 404 instead of 403.

**Comment by DESHRAJ** [comment]
@Shivam1904 please check if this is done and close it after that. :)

**Comment by Shivam1904** [comment]
@DESHRAJ  Done, refer #38

**Comment by DESHRAJ** [comment]
Ok cool...closing it :+1:
