### ISSUE TITLE
Integrate full text search using haystack and normal searching in MySQL 

### ISSUE THREAD

**Issue by DESHRAJ** [ncs-jss/HTTP_200#26]

**Comment by DESHRAJ** [comment]
We will be using haystack for full text search for mysql or postgres backend and along with other filtering options according to : 
1. Branch 
2. Year
3. Faculty
4. Department
5. Subject 

@shriyanka @Shivam1904 @RishabhJain2018 please let me know if we should add some other filters for notices search.

**Comment by shriyanka** [comment]
@DESHRAJ  its good for now. I don't think we need some more information here. I feel you are referencing Department to category field in Notice Models. 
We can think of including the `created_at` field too coz students do search the notices on basis of dates on which they were published. So if its good in haystack, then we can think of including it.

**Comment by DESHRAJ** [comment]
Fixed in v1.1
