### ISSUE TITLE
Repeated code in Profiles/models.py 

### ISSUE THREAD

**Issue by shriyanka** [ncs-jss/HTTP_200#32]
![screenshot from 2015-12-02 13 40 13](https://cloud.githubusercontent.com/assets/9421351/11525584/477066b2-98fa-11e5-8ac4-e3569eff56e2.png)

Why so?

**Comment by DESHRAJ** [comment]
@shriyanka can you specify the line numbers ? I am not getting the issue exactly.

**Comment by shriyanka** [comment]
@DESHRAJ line 49-56 and 65-73

**Comment by DESHRAJ** [comment]
Ok got it. It is the redundant code that needs to be removed. Assigning it to you.
