### ISSUE TITLE
Use BranchYear model while saving the notices

### ISSUE THREAD

**Issue by DESHRAJ** [ncs-jss/HTTP_200#34]
The BranchYear table is not filled up when the notices are created. The form_valid method should be overriden so as to get this working.

**Comment by DESHRAJ** [comment]
@Shivam1904 any update on this ?

**Comment by Shivam1904** [comment]
@DESHRAJ Is it the duplicate of #44 ?

**Comment by DESHRAJ** [comment]
Yes, it ism. Close if fixed.

**Comment by DESHRAJ** [comment]
Fixed. Closing it now.
