### ISSUE TITLE
creating "pin it to top" option in bookmarks

### ISSUE THREAD

**Issue by shriyanka** [ncs-jss/HTTP_200#42]
Certain user might wish to keep a Bookmark at top so he has to not scroll down. So we can have this enhancment feature same as FB.. Pinning the bookmark to top.  It can be for later version if not right now.

**Comment by DESHRAJ** [comment]
Great idea. We can add this feature as well. :+1: Lets do this in v1.2

**Comment by shriyanka** [comment]
@deshraj

should we close this issue?? I think its done for now or do we need somthing more in it??

**Comment by DESHRAJ** [comment]
Yeah, it can be closed now. Closing it. Great work :)
