### ISSUE TITLE
Template for creating a new user

### ISSUE THREAD

**Issue by DESHRAJ** [ncs-jss/HTTP_200#46]
This involves:
a) Create backend logic for creating a new user
b) Create a template for the same

We need to have a discussion that should we use the django admin or we should create the templates by our own.

**Comment by Curious72** [comment]
@DESHRAJ Can i have a look at it?

**Comment by DESHRAJ** [comment]
Yes @Curious72 you can work on this. Just some minor modifications we have made after discussing with @shriyanka yesterday that the users will be created on the django admin only and we dont need to create new templates for that. So. just make sure that
1. faculty and user object(related to that faculty) are created on the django admin page of faculty 
2. student and user object(related to that student) are created on the django admin page of student. 

@Curious72  Let me know if this is not clear.

**Comment by DESHRAJ** [comment]
Assigning this to @Curious72

**Comment by DESHRAJ** [comment]
After discussion, it looks like we are not creating new template for creating the new user. So, lets close this issue now. @Curious72 if you are willing to contribute, then you can pick some other bug and work on it. :+1:
