### ISSUE TITLE
Option to send notices to few people only

### ISSUE THREAD

**Issue by DESHRAJ** [ncs-jss/HTTP_200#49]
If someone is uploading the notice, then he/she should be able to set the option that whom he/she wants to send the notice. It may be specific to HODs only, Principal only or public and many more.

**Comment by Curious72** [comment]
@DESHRAJ  I would like to work on this issue !

**Comment by DESHRAJ** [comment]
@Curious72 , Kajal( @shriyanka) have already started and you can see a PR made by her. Please pick any other issue adn we are good to go.

**Comment by shriyanka** [comment]
@DESHRAJ  we were talking about messages. how come notice?? Are we on same page? :smile:

**Comment by shriyanka** [comment]
same as issue #48

**Comment by DESHRAJ** [comment]
Implemented. Closing it now.
