### ISSUE TITLE
Create 404/500 template page

### ISSUE THREAD

**Issue by DESHRAJ** [ncs-jss/HTTP_200#5]

**Comment by RishabhJain2018** [comment]
Sir, Can you please suggest where to put these templates?

**Comment by DESHRAJ** [comment]
@RishabhJain2018 can you create a pull request of the template pages that you have developed ?

**Comment by shriyanka** [comment]
OHh sorry I didn't see the comments.. Rishabh was working on it ?

**Comment by DESHRAJ** [comment]
Yes, @RishabhJain2018  was working on this issue. For now, its ok that you have made changes but lets assign the issues before working on it so that everyone is aware of the assigned bugs.
