### ISSUE TITLE
Redirecting users on complete your profile page when any user logs in for the first time

### ISSUE THREAD

**Issue by deshraj** [ncs-jss/HTTP_200#56]
Once the user is created by the admin and as the user arrives the login page and tries to login then he should be redirected to the "complete your profile" page. After successfully filling the details, then only he can go ahead and perform the further transactions.

**Comment by shriyanka** [comment]
@DESHRAJ @Shivam1904 I think we should do same thing for a person doing signup from webpage. As he signs up he should be re-directed to "complete your profile" page. and same as above.

**Comment by Shivam1904** [comment]
@shriyanka - As discussed with @DESHRAJ , there will be no signups from webpage. All the signups/adding user will be only from admin panel. The current signup feature from webpage will be removed.

**Comment by shriyanka** [comment]
ohho. we are not on same page regarding details. ok will be closing the PR then. we do not need it now

**Comment by RishabhJain2018** [comment]
@DESHRAJ Can I work on this issue?

**Comment by DESHRAJ** [comment]
Sure @RishabhJain2018 you can.

**Comment by DESHRAJ** [comment]
Assigning to @RishabhJain2018

**Comment by DESHRAJ** [comment]
@RishabhJain2018 any progress ? Do ping me if you need some help.

**Comment by RishabhJain2018** [comment]
@DESHRAJ sure sir...

**Comment by RishabhJain2018** [comment]
@DESHRAJ Sir,  which model fields in student's profile are to be made required?

**Comment by DESHRAJ** [comment]
@RishabhJain2018 write a decorator named `profile_completed` in which you will check that if the details like branch, year, semester and other personal details(first name, lastname, email and phone number) are filled or not. If these details are not filled, then redirect the user to Complete your profile page.

**Comment by RishabhJain2018** [comment]
@DESHRAJ  sure sir.
