### ISSUE TITLE
Bulk user generation using CSV and simple registration form 

### ISSUE THREAD

**Issue by deshraj** [ncs-jss/HTTP_200#57]

**Comment by DESHRAJ** [comment]
The admin has the right to create bulk users either through CSV or through simple resgirtation form. 

1. Using CSV: 

Just upload a csv with the usernames and passwords and tick the group in which he wants to create the users.

2. Using Registration form: 

Following fields will be there : 
         1. Starting RollNo
         2. Ending Roll Number
         3. Branch
         4. Year prefix

So, for example, for creating 12cse030, 

branch - > cse
year prefix - > 12

**Comment by Curious72** [comment]
@DESHRAJ  the first method is accomplished  i guess using the import functionality added by the PR #60 !! Will the usernames for the second method be roll no.s of students?

**Comment by DESHRAJ** [comment]
@Curious72 do you want to take this up ? And yes the first method is accomplished.

**Comment by Curious72** [comment]
@DESHRAJ Yeah sure  !!

**Comment by DESHRAJ** [comment]
Assigned. :+1:

**Comment by Curious72** [comment]
@DESHRAJ  How will be determine the username in case of registration form?

**Comment by DESHRAJ** [comment]
@Curious72 so here is the explaination of how it will work. 

You will have a form with fields ``starting_roll_number`` ``last_roll_number`` ``branch``  and ``year``.

For example if I want to create first 50 students of ``CS`` branch of batch starting in 2012 then the values of the fields will be : 

``starting_roll_number``  = 1
``last_roll_number`` = 50 
``branch`` = CS 
 ``year`` = 12

After this, you just need to create the entries in the backend by running queries. I hope I am clear. Let me know if you still have doubts.
