### ISSUE TITLE
Export CSV option on admin 

### ISSUE THREAD

**Issue by DESHRAJ** [ncs-jss/HTTP_200#58]
Suppose admin wants to export the data of students of a particular class or any group of students, then he can have the export csv option on the django admin panel.

**Comment by DESHRAJ** [comment]
We will be using https://django-import-export.readthedocs.org/en/latest/index.html

**Comment by DESHRAJ** [comment]
@Curious72 do you want to work on this ??

**Comment by Curious72** [comment]
@DESHRAJ Yes Surely !!

**Comment by DESHRAJ** [comment]
assigning it to you @Curious72

**Comment by DESHRAJ** [comment]
@Curious72 is this done ??

**Comment by Curious72** [comment]
@DESHRAJ Yes !!

**Comment by DESHRAJ** [comment]
@Curious72 cool then. Closing it now.
