### ISSUE TITLE
Improve the schema so that less queries execute when we create a notice

### ISSUE THREAD

**Issue by DESHRAJ** [ncs-jss/HTTP_200#68]
Currently, when we are creating a notice then we run the following queries: 

`    
    
    Notice.objects.create(...)
   
    for i in branch:
        for j in year:
            NoticeBranchYear.objects.create(...)    
`
I think this will make our system really slow and we should optimize this. 

What I have in mind right now is adding two fields in Notice table:
1. `Branch`(CharField)
2. `Year` (CharField)

where both will store the Branches and Years separated by spaces like `Branch = CSE IT ECE EE` and Year = `1 2 3 4`

@shriyanka @Shivam1904 @Curious72 @abhisheksachan need your reviews guys.

**Comment by Curious72** [comment]
@DESHRAJ That way there would be no need for NoticeBranchYear model !!

**Comment by shriyanka** [comment]
@DESHRAJ  or what we can do is create a conts file and keep the constants in it like this
BRANCH = ((IT,'it'),(CS,'cs').......)
YEAR = ('1','2','3','4')
and while making a query we do:
branch=request.get('branch')
year = request.get('year')
if branch in conts.branch and year in conts.year then run query else fail
no looping.

**Comment by DESHRAJ** [comment]
@Curious72 Yes you are right. Thats exactly what I am thinking. :+1: 

@shriyanka I dont think we need to store constants because we would then need to make unnecessary imports and we dont need to store these branches and year somewhere because we dont need them and they will be changing from time to time. And yes we are on the same page. :)

**Comment by shriyanka** [comment]
@DESHRAJ  Okay :+1: Then change the schema.. Its good we are changing at such an early stage +1 for it

**Comment by DESHRAJ** [comment]
Fixed. Closing it.
