### ISSUE TITLE
Create FAQ template page

### ISSUE THREAD

**Issue by DESHRAJ** [ncs-jss/HTTP_200#7]

**Comment by shriyanka** [comment]
@DESHRAJ Is this dynamic i.e a separate model is to be created for storing QA and later displaying and updating it for ease of administration ?? Or simple a static template is good for now??

**Comment by DESHRAJ** [comment]
No, this will be only a static page of how to use the web application. I will provide you the details soon.

**Comment by shriyanka** [comment]
@Deshraj This is done.. We need to add questions only

**Comment by DESHRAJ** [comment]
Ok I am closing it as it seems to be done by @infinitegarg on the client side. For now, we are donw with this issue.
