### ISSUE TITLE
TypeError at /notices/relevant/

### ISSUE THREAD

**Issue by JINDALG** [ncs-jss/HTTP_200#90]
when open relevant page it show :-
 unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by DESHRAJ** [comment]
@JINDALG can you send me a screenshot of this ?

**Comment by JINDALG** [comment]
sorry sir,  don't know how but now it is showing well

**Comment by DESHRAJ** [comment]
No worries, keep coming up issues. Lets make it totally bug free. :stuck_out_tongue_winking_eye:
