### ISSUE TITLE
Heavy loader

### ISSUE THREAD

**Issue by itaditya** [ncs-jss/HTTP_200#92]
the preloader is of 400kb but we can use css preloader much lighter one , i have made some 

Preview -- https://codepen.io/itaditya/pen/xVjvXv , https://codepen.io/itaditya/pen/vGVVEB

Should I integrate it or leave this

**Comment by aka-jain** [comment]
Good work @itaditya but can you make the existed loader by CSS? The loaders that you have made will not look that much perfect with the current design and for now I have compressed it to 53 KB.

If it is possible then redraw the existing loader by CSS and integrate it.

**Comment by itaditya** [comment]
Okay Sir , I will try this
