### ISSUE TITLE
Contact Field Validation in Update Profile Page

### ISSUE THREAD

**Issue by abhayraw1** [ncs-jss/HTTP_200#95]
The contact field in update profile page isn't validated for numbers in both frontend and backend.

**Comment by DESHRAJ** [comment]
Good catch @abhayraw1 . We will fix it before launching on production.

**Comment by DESHRAJ** [comment]
@Shivam1904 Can you fix this ? Assigning it to you.

**Comment by DESHRAJ** [comment]
Fixed :+1:
